#!/usr/bin/env bash
# Nexus — interactive setup script
# Usage: chmod +x setup.sh && ./setup.sh
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info()    { echo -e "${CYAN}[nexus]${RESET} $*"; }
success() { echo -e "${GREEN}[nexus]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[nexus]${RESET} $*"; }
die()     { echo -e "${RED}[nexus] ERROR:${RESET} $*" >&2; exit 1; }

echo -e "${BOLD}"
echo "  ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗"
echo "  ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝"
echo "  ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗"
echo "  ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║"
echo "  ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║"
echo "  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝"
echo -e "${RESET}"
echo "  Nexus Setup — Privacy-first communication platform"
echo ""

# ── Prerequisite checks ───────────────────────────────────────────────────────
info "Checking prerequisites..."

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        die "$1 is not installed. Please install it and re-run setup."
    fi
    success "$1 found"
}

check_cmd docker
check_cmd curl
check_cmd openssl

if ! docker compose version &>/dev/null; then
    die "Docker Compose v2 not available. Run: docker plugin install docker/compose-plugin"
fi
success "Docker Compose v2 found"
echo ""

# ── Gather configuration ──────────────────────────────────────────────────────
info "Configuration"
echo ""

read -rp "  Server domain (e.g. nexus.example.com): " NEXUS_DOMAIN
[[ -z "$NEXUS_DOMAIN" ]] && die "Domain is required."

read -rp "  Admin email (for TLS cert notifications): " ADMIN_EMAIL
[[ -z "$ADMIN_EMAIL" ]] && die "Admin email is required."

echo ""

# ── Generate secrets ──────────────────────────────────────────────────────────
info "Generating secrets..."
JWT_SECRET=$(openssl rand -hex 64)
POSTGRES_PASSWORD=$(openssl rand -hex 32)
REDIS_PASSWORD=$(openssl rand -hex 32)
MINIO_PASSWORD=$(openssl rand -hex 32)
MEILI_KEY=$(openssl rand -hex 32)
success "Secrets generated"
echo ""

# ── Write .env.prod ───────────────────────────────────────────────────────────
ENV_FILE=".env.prod"
info "Writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file to version control.

NEXUS_DOMAIN=${NEXUS_DOMAIN}
NEXUS_ADMIN_EMAIL=${ADMIN_EMAIL}

NEXUS_JWT_SECRET=${JWT_SECRET}
NEXUS_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NEXUS_REDIS_PASSWORD=${REDIS_PASSWORD}
NEXUS_MINIO_PASSWORD=${MINIO_PASSWORD}
NEXUS_MEILI_KEY=${MEILI_KEY}
EOF

chmod 600 "$ENV_FILE"
success "$ENV_FILE written (permissions 600)"
echo ""

# ── Write Caddyfile ───────────────────────────────────────────────────────────
CADDY_FILE="deploy/Caddyfile"
if [[ ! -f "$CADDY_FILE" ]]; then
    info "Writing $CADDY_FILE..."
    cat > "$CADDY_FILE" <<EOF
${NEXUS_DOMAIN} {
    reverse_proxy /api/*            nexus:8080
    reverse_proxy /ws               nexus:8081
    reverse_proxy /_nexus/*         nexus:8448
    reverse_proxy /.well-known/nexus/* nexus:8448
    reverse_proxy /_matrix/*        nexus:8448
}
EOF
    success "Caddyfile written"
fi
echo ""

# ── Pull images ───────────────────────────────────────────────────────────────
info "Pulling Docker images (this may take a few minutes)..."
docker compose -f deploy/docker-compose.prod.yml --env-file "$ENV_FILE" pull
echo ""

# ── Run DB migrations ─────────────────────────────────────────────────────────
info "Starting dependencies for initial migration..."
docker compose -f deploy/docker-compose.prod.yml --env-file "$ENV_FILE" \
    up -d postgres redis scylla meilisearch minio

info "Waiting for PostgreSQL to be ready..."
until docker compose -f deploy/docker-compose.prod.yml --env-file "$ENV_FILE" \
    exec -T postgres pg_isready -U nexus &>/dev/null; do
    sleep 2
done
success "PostgreSQL ready"
echo ""

# ── Start full stack ──────────────────────────────────────────────────────────
info "Starting Nexus..."
docker compose -f deploy/docker-compose.prod.yml --env-file "$ENV_FILE" up -d
echo ""

# ── Health check ──────────────────────────────────────────────────────────────
info "Waiting for Nexus to be ready..."
for i in $(seq 1 20); do
    if curl -sf "http://localhost:8080/api/v1/health" &>/dev/null; then
        success "Nexus is up! 🎉"
        break
    fi
    sleep 3
    if [[ $i -eq 20 ]]; then
        warn "Health check timed out. Check logs with:"
        warn "  docker compose -f deploy/docker-compose.prod.yml logs nexus"
    fi
done

echo ""
echo -e "${BOLD}${GREEN}Setup complete!${RESET}"
echo ""
echo "  🌍  https://${NEXUS_DOMAIN}"
echo "  📋  Logs:   docker compose -f deploy/docker-compose.prod.yml logs -f nexus"
echo "  🔄  Update: docker compose -f deploy/docker-compose.prod.yml pull && docker compose up -d"
echo "  📖  Docs:   https://github.com/The-No-hands-Company/Nexus/tree/main/docs"
echo ""
echo -e "${YELLOW}  ⚠  Keep .env.prod safe — it contains all your secrets.${RESET}"
echo ""
